# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeaWorld-AR-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeaWorld-AR-Demo
  pod 'SCNVideoWriter', :git => 'https://github.com/Papercloud/SCNVideoWriter.git'
  pod 'Spine', :git => 'https://github.com/json-api-ios/Spine.git'
  pod 'SeaworldARFramework', :git => 'https://github.com/Papercloud/SeaWorldARExperience.git'

end
